name: Publish package

on: workflow_dispatch

permissions:
    contents: write
    id-token: write

jobs:
    publish_package:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.1.34

            - id: changelog
              name: Generate changelog
              run: bun scripts/generate-changelog.ts

            - name: Install modules
              run: bun install

            - name: Type-check
              run: tsc --noEmit

            - name: Publish package to NPM
              run: bun publish --access public
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Rename to elysia-remix
              run: npm pkg set name=elysia-remix

            - name: Publish package to NPM as elysia-remix
              run: bun publish --access public
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: GitHub Release
              uses: ncipollo/release-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: v${{ steps.changelog.outputs.version }}
                  name: v${{ steps.changelog.outputs.version }}
                  body: ${{ steps.changelog.outputs.changelog }}
                  draft: false
                  prerelease: false
                  generateReleaseNotes: true
